version: '3'
x-aws-loadbalancer: "questring-load-balancer"
services:
  server:
    image: 645943600532.dkr.ecr.us-east-1.amazonaws.com/server:v0.1
    command: bundle exec puma -e production -C config/puma.rb
    environment:
      RAILS_ENV: production
    secrets:
      - server_secret
    x-aws-policies:
      - "arn:aws:iam::645943600532:policy/ecs-exec-policy"
  nginx:
    image: 645943600532.dkr.ecr.us-east-1.amazonaws.com/nginx:v0.1
    ports:
      - "8080:8080"
    depends_on:
      - server
secrets:
  server_secret:
    name: "arn:aws:secretsmanager:us-east-1:645943600532:secret:qeq-mysql-uVQkdT"
    external: true
