version: '3'
services:
  server:
    image: 645943600532.dkr.ecr.us-east-1.amazonaws.com/server:v0.1
    command: bundle exec puma -e production -C config/puma.rb
    environment:
      RAILS_ENV: production
    secrets:
      - server_secret
    x-aws-role: &aws-role
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Action:
          - ssmmessages:CreateControlChannel
          - ssmmessages:CreateDataChannel
          - ssmmessages:OpenControlChannel
          - ssmmessages:OpenDataChannel
        Resource: '*'
  front:
    image: 645943600532.dkr.ecr.us-east-1.amazonaws.com/front:v0.1
    ports:
      - 80:80
    depends_on:
      - server
    x-aws-role: *aws-role
secrets:
  server_secret:
    name: "arn:aws:secretsmanager:us-east-1:645943600532:secret:qeq-mysql-uVQkdT"
    external: true
