version: '3'
services:
  server:
    image: 645943600532.dkr.ecr.us-east-1.amazonaws.com/server:v0.1
    command: bundle exec puma -e production -C config/puma.rb
  nginx:
    image: 645943600532.dkr.ecr.us-east-1.amazonaws.com/nginx:v0.1
    ports:
      - "80:80"
    depends_on:
      - server
