version: '3'

# 管轄外
#
# up前
# - RDS
#   - 作っておく
# - SecretsManager
#   - RDSの鍵管理
# - Certificate Manager
#   - 証明書の取得など
# - ECR
#   - リポジトリ作り
# up後
# - Route53
#   - ALBにドメインを紐付ける
# - VPC
#   - RDSが所属するセキュリティグループのインバウンドルールに、
#     ECSが所属するセキュリティグループからの通信を許可する

services:
  server:
    image: 645943600532.dkr.ecr.us-east-1.amazonaws.com/server:v0.1
    command: bundle exec puma -e production -C config/puma.rb
    environment:
      RAILS_ENV: production
    secrets:
      - server_secret
    x-aws-role: &aws-role
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Action:
          - ssmmessages:CreateControlChannel
          - ssmmessages:CreateDataChannel
          - ssmmessages:OpenControlChannel
          - ssmmessages:OpenDataChannel
        Resource: '*'
  front:
    image: 645943600532.dkr.ecr.us-east-1.amazonaws.com/front:v0.1
    ports:
      - 80:80
    depends_on:
      - server
    x-aws-role: *aws-role

secrets:
  server_secret:
    name: "arn:aws:secretsmanager:us-east-1:645943600532:secret:searchsearch-mysql-uVQkdT"
    external: true

x-aws-cloudformation:
  Resources:
    ServerService:
      Properties:
        EnableExecuteCommand: true
    FrontService:
      Properties:
        EnableExecuteCommand: true
    FrontTCP80Listener:
      # リスナーはHTTPSの443, ターゲットグループはHTTPの80 にするためにリスナー側を上書きしている
      Properties:
        Certificates:
          - CertificateArn: "arn:aws:acm:us-east-1:645943600532:certificate/e615cd30-4571-4cd1-be8d-3ceb67ab6b84"
        Protocol: HTTPS
        Port: 443
