version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "4306:3306"
    volumes:
        - ./server/db/mysql_data:/var/lib/mysql
  server:
    build: ./server
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - ./server:/app
      - gem_data:/usr/local/bundle
    ports:
      - "5000:5000"
    depends_on:
      - db
  front:
    build: ./front
    volumes:
     - ./front:/usr/src/app
     - yarn-cache:/usr/local/share/.cache/yarn/v2
    command: sh -c "npm start"
    ports:
     - "3000:3000"
    links:
      - server
volumes:
  gem_data:
  yarn-cache:
